### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by tboonf** [frankkramer-lab/rBiopaxParser#1]
Hi, 
I received the following error when I was installing rBiopaxParser:

Installing github repo(s) rBiopaxParser/master from frankkramer
Installing rBiopaxParser.zip from https://api.github.com/repos/frankkramer/rBiopaxParser/zipball/master
Installing rBiopaxParser
C:/PROGRA~1/R/R-devel/bin/x64/R --vanilla CMD build  \
  "C:\Users\leonard\AppData\Local\Temp\RtmpkTG9wI\frankkramer-rBiopaxParser-bf9bd29" --no-manual  \
  --no-resave-data 
- checking for file 'C:\Users\leonard\AppData\Local\Temp\RtmpkTG9wI\frankkramer-rBiopaxParser-bf9bd29/DESCRIPTION' ... OK
- preparing 'rBiopaxParser':
- checking DESCRIPTION meta-information ... OK
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- building 'rBiopaxParser_0.15.tar.gz'
  ERROR
  packaging into .tar.gz failed
  Error: Command failed (1)
  In addition: Warning message:
  running command '"C:/PROGRA~1/R/R-devel/bin/x64/R" --vanilla CMD build "C:\Users\leonard\AppData\Local\Temp\RtmpkTG9wI\frankkramer-rBiopaxParser-bf9bd29" --no-manual --no-resave-data' had status 1 

I hope you can point me the problem. Thanks!
Cheers,

**Comment by frankkramer** [comment]
Hi tboonf,

package building under Windows might require Rtools. Do you have Rtools correctly installed? 
It can be obtained from http://cran.r-project.org/bin/windows/Rtools/
Another caveat with Windows is the Path enviroment variable. The following thread might help you with the Path variable:
https://stat.ethz.ch/pipermail/r-help/2011-September/289183.html

Cheers,
Frank Kramer
