### ISSUE TITLE
downloading reactome data issue

### ISSUE THREAD

**Issue by szimmerman92** [frankkramer-lab/rBiopaxParser#3]
Hi,
When I ran the command 

file = downloadBiopaxData("reactome","reactome", version="biopax3")

I received the error 

Error in unz(outputfile, "Homo sapiens.owl", open = "rb") : 
  cannot open the connection
In addition: Warning message:
In unz(outputfile, "Homo sapiens.owl", open = "rb") :
  cannot locate file 'Homo sapiens.owl' in zip file 'biopax.zip'

I believe the reason for this is that the name of the file inside biopax.zip is not 'Homo sapiens.owl' but 'Homo_sapiens.owl'. Is this correct or am I just doing something incorrectly? If that is the reason, do you know how I could fix it?

Thank you!

**Comment by cannin** [comment]
It does look like the Reactome group added in underscores (in December, from looking at the timestamps). You can download the file directly (the homo sapiens file is in the zip file): 

http://www.reactome.org/download/current/biopax.zip

I looked at the code: 

https://github.com/frankkramer/rBiopaxParser/blob/master/R/downloadBiopaxData.R

to get that URL.

**Comment by frankkramer** [comment]
Hi,

Thanks for taking the time to explain this, cannin!
I will fix this with the next batch of fixes/updates.

Best wishes,
Frank

**Comment by frankkramer** [comment]
This has been fixed.
